# Generated by Django 6.0.4 on 2026-04-20 14:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_grant_personnel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='systemverificationgrant',
            name='full_administration',
            field=models.BooleanField(default=False, help_text='Si es verdadero, la cuenta enlazada recibio is_staff/is_superuser al otorgar este permiso.'),
        ),
        migrations.AddField(
            model_name='systemverificationgrant',
            name='promoted_user',
            field=models.ForeignKey(blank=True, help_text='Usuario al que se elevo a staff al crear este permiso (se revierte al revocar).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verification_grant_promotions', to=settings.AUTH_USER_MODEL),
        ),
    ]
