# Generated by Django 6.0.4 on 2026-04-23 04:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_panel_modules(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    PanelUserModulePermission = apps.get_model('authentication', 'PanelUserModulePermission')
    legacy = ['dashboard', 'inventario', 'estadisticas']
    for u in User.objects.filter(is_staff=False, is_superuser=False):
        PanelUserModulePermission.objects.get_or_create(user_id=u.pk, defaults={'modules': legacy})


def noop_backfill(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_grant_full_administration'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PanelUserModulePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modules', models.JSONField(default=list)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='panel_module_permission', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Permisos de modulos (panel)',
                'verbose_name_plural': 'Permisos de modulos (panel)',
            },
        ),
        migrations.RunPython(backfill_panel_modules, noop_backfill),
    ]
