# Generated by Django 6.0.4 on 2026-05-01 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0003_customer_sale_customer_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='credit_days',
            field=models.PositiveSmallIntegerField(default=0, help_text='Días de plazo para ventas a crédito (0 = sin plazo definido).'),
        ),
        migrations.AddField(
            model_name='sale',
            name='credit_note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='sale',
            name='payment_status',
            field=models.CharField(choices=[('paid', 'Pagado'), ('credit', 'Crédito'), ('pending', 'Pago pendiente')], default='paid', max_length=16),
        ),
    ]
