# Generated by Django 6.0.4 on 2026-05-01 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0004_add_payment_status_to_sale'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Descuento fijo aplicado al total (en quetzales).', max_digits=10),
        ),
    ]
