# Generated by Django 6.0.4 on 2026-05-04 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0005_add_discount_to_sale'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='nit',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
    ]
