# Generated by Django 6.0.4 on 2026-05-04 22:28

from decimal import Decimal

from django.db import migrations, models
from django.db.models import F


def backfill_amount_paid(apps, schema_editor):
    Sale = apps.get_model('pos', 'Sale')
    Sale.objects.filter(payment_status='paid').update(amount_paid=F('total'))
    Sale.objects.exclude(payment_status='paid').update(amount_paid=Decimal('0'))


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0006_customer_nit'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Suma de abonos recibidos (crédito/pendiente). Si alcanza el total, la venta queda pagada.', max_digits=12),
        ),
        migrations.RunPython(backfill_amount_paid, migrations.RunPython.noop),
    ]
