# Generated by Django 6.0.4 on 2026-04-15 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PersonnelRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dpi', models.CharField(db_index=True, max_length=32, unique=True)),
                ('nombre', models.CharField(max_length=200)),
                ('puesto', models.CharField(max_length=120)),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo'), ('SUSPENDIDO', 'Suspendido')], default='ACTIVO', max_length=20)),
                ('permisos', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Registro de personal',
                'verbose_name_plural': 'Registros de personal',
                'ordering': ['nombre'],
            },
        ),
    ]
