# Generated by Django 6.0.4 on 2026-04-20 15:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0004_personnelrecord_telefono_dpi'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='personnelrecord',
            name='panel_user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='boutique_personnel', to=settings.AUTH_USER_MODEL, verbose_name='Usuario de panel (Ingresar)'),
        ),
    ]
