# Generated by Django 6.0.4 on 2026-04-20 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0005_personnel_panel_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dias', models.CharField(blank=True, default='', help_text='Ej.: Lun a Vie', max_length=200)),
                ('hora_entrada', models.TimeField()),
                ('hora_salida', models.TimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('personnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_schedules', to='hr.personnelrecord')),
            ],
            options={
                'verbose_name': 'Horario de trabajo',
                'verbose_name_plural': 'Horarios de trabajo',
                'ordering': ['personnel_id', 'hora_entrada', 'id'],
            },
        ),
    ]
