# Generated by Django 6.0.4 on 2026-04-16 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0001_initial'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventoryitem',
            options={'ordering': ['branch', 'line', 'display_order', 'name']},
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='display_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='line',
            field=models.CharField(choices=[('ropa-dama', 'Ropa nueva de dama'), ('ropa-caballero', 'Ropa nueva de caballero')], default='ropa-dama', max_length=32),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='sku',
            field=models.CharField(max_length=50),
        ),
        migrations.AddConstraint(
            model_name='inventoryitem',
            constraint=models.UniqueConstraint(fields=('branch', 'sku', 'line'), name='inventory_item_branch_sku_line_uniq'),
        ),
    ]
