# Generated by Django 6.0.4 on 2026-04-20 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_add_line_display_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='image',
            field=models.ImageField(blank=True, help_text='Foto del producto (opcional).', null=True, upload_to='inventory/items/%Y/%m/'),
        ),
    ]
