# Generated by Django 6.0.4 on 2026-04-22 00:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_inventoryitem_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('line', models.CharField(blank=True, choices=[('ropa-dama', 'Ropa nueva de dama'), ('ropa-caballero', 'Ropa nueva de caballero')], default='', help_text='Vacío: la categoría aplica a cualquier línea.', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['line', 'name'],
                'constraints': [models.UniqueConstraint(fields=('name', 'line'), name='inventory_category_name_line_uniq')],
            },
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='inventory.productcategory'),
        ),
    ]
