# Generated by Django 6.0.4 on 2026-04-22 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_product_category_and_item_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='packages_per_fardo',
            field=models.PositiveIntegerField(default=1, help_text='Cuántos paquetes entran en un fardo.'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='units_per_package',
            field=models.PositiveIntegerField(default=1, help_text='Cuántas unidades (piezas) entran en un paquete.'),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='quantity',
            field=models.PositiveIntegerField(default=0, help_text='Stock total expresado en unidades (pieza mínima).'),
        ),
    ]
