# Generated by Django 6.0.4 on 2026-04-22 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_inventory_unit_hierarchy'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Precio de costo por unidad (pieza).', max_digits=10),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, help_text='Precio de venta por unidad (pieza).', max_digits=10),
        ),
    ]
