# Generated by Django 6.0.4 on 2026-04-29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('inventory', '0006_inventory_cost_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='fardo_price',
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text='Precio de venta por fardo (captura directa, sin conversiones).',
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='package_price',
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text='Precio de venta por paquete (captura directa, sin conversiones).',
                max_digits=10,
            ),
        ),
    ]

