# Generated by Django 6.0.4 on 2026-05-06 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_inventory_package_fardo_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Borrado lógico: marcar False oculta el producto del catálogo pero conserva ventas históricas.'),
        ),
    ]
