# Generated by Django 6.0.4 on 2026-04-20 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='maps_url',
            field=models.CharField(blank=True, default='', help_text='Enlace o URL corta de Google Maps (compartir ubicacion de la sucursal).', max_length=800),
        ),
    ]
