# Generated by Django 6.0.4 on 2026-05-06 21:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pos', '0007_add_amount_paid_to_sale'),
    ]

    operations = [
        migrations.CreateModel(
            name='FelEmisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('nit', models.CharField(help_text='NIT del emisor (solo números, sin guion).', max_length=40, unique=True)),
                ('nombre_comercial', models.CharField(blank=True, default='', max_length=200)),
                ('codigo_establecimiento', models.PositiveIntegerField(default=1)),
                ('afiliacion_iva', models.CharField(choices=[('GEN', 'Régimen general'), ('PEQ', 'Pequeño contribuyente'), ('EXE', 'Exento')], default='GEN', max_length=8)),
                ('direccion', models.CharField(max_length=300)),
                ('codigo_postal', models.CharField(default='01001', max_length=10)),
                ('municipio', models.CharField(default='GUATEMALA', max_length=100)),
                ('departamento', models.CharField(default='GUATEMALA', max_length=100)),
                ('pais', models.CharField(default='GT', max_length=4)),
                ('ambiente', models.CharField(choices=[('pruebas', 'Pruebas'), ('produccion', 'Producción')], default='pruebas', max_length=16)),
                ('requestor', models.CharField(blank=True, default='', help_text='GUID del requestor de Corpo (vacío = se toma de la variable FEL_REQUESTOR).', max_length=80)),
                ('username', models.CharField(blank=True, default='', help_text='Usuario para Corpo (vacío = se toma de FEL_USERNAME, por defecto ADMINISTRADOR).', max_length=80)),
                ('is_default', models.BooleanField(default=True, help_text='Emisor a usar cuando no se elige uno en concreto.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Emisor FEL',
                'verbose_name_plural': 'Emisores FEL',
                'ordering': ['-is_default', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='FelDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('certificado', 'Certificado'), ('rechazado', 'Rechazado'), ('error', 'Error')], default='pendiente', max_length=16)),
                ('ambiente', models.CharField(choices=[('pruebas', 'Pruebas'), ('produccion', 'Producción')], default='pruebas', max_length=16)),
                ('serie', models.CharField(blank=True, default='', max_length=40)),
                ('numero_autorizacion', models.CharField(blank=True, default='', max_length=80)),
                ('fecha_certificacion', models.DateTimeField(blank=True, null=True)),
                ('xml_enviado', models.TextField(blank=True, default='')),
                ('xml_certificado', models.TextField(blank=True, default='')),
                ('respuesta_cruda', models.TextField(blank=True, default='')),
                ('error_mensaje', models.TextField(blank=True, default='')),
                ('intentos', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sale', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fel', to='pos.sale')),
                ('emisor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentos', to='fel.felemisor')),
            ],
            options={
                'verbose_name': 'Documento FEL',
                'verbose_name_plural': 'Documentos FEL',
                'ordering': ['-created_at'],
            },
        ),
    ]
