# Generated by Django 6.0.4 on 2026-05-01 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0002_supplier_nit_razon_social_name_optional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='contact',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Contacto'),
        ),
    ]
