# Generated by Django 6.0.4 on 2026-05-06 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0003_sync_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Borrado lógico: oculta la orden del listado pero conserva el histórico de stock.'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Borrado lógico: marcar False oculta el proveedor de las listas pero conserva órdenes históricas.'),
        ),
    ]
